name: Tests

on:
  push:
  workflow_dispatch:  # Allows manual runs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip and install build tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install package (editable)
        run: pip install -e .

      - name: Install test dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest
